/* aiflib.h — the aowl system runtime for the aoughwl native backend.
 *
 * Hand-written C runtime that provides the `system` / `syncio` symbols a
 * post-hexer `.c.nif` references, so real nimony programs link natively
 * through aifc (https://github.com/aoughwl/aifc) with no nimony `system.c.nif`.
 *
 * Per the aoughwl convention this hand-written C is the *bootstrap seed &
 * oracle* for the eventual aowl-native `system` module.
 *
 * Canonical types & entry points are named `aiflib_*` / `Aiflib*` and are
 * hash-independent.  A per-program shim (generated by bin/aiflib-cc) aliases
 * the module-hashed names a given `.c.nif` uses (e.g. `write_0_syn1lfpjv`) onto
 * these.  See docs/runtime.md.
 */
#ifndef AIFLIB_H
#define AIFLIB_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* ---- NIF primitive typedefs (mirror aifc's PRELUDE; C11 permits identical
 *      typedef redefinition, so co-inclusion with aifc output is safe). ---- */
typedef unsigned char NC8;
typedef uint16_t NC16;
typedef uint32_t NC32;
typedef float  NF32;
typedef double NF64;
typedef double NF;
typedef int8_t  NI8;  typedef int16_t  NI16; typedef int32_t  NI32; typedef int64_t  NI64;
typedef uint8_t NU8;  typedef uint16_t NU16; typedef uint32_t NU32; typedef uint64_t NU64;
typedef NI64 NI;      typedef NU64 NU;
typedef _Bool NB8;

/* ---- SSO string constants (mirror lib/std/system/stringimpl.nim) ---- */
#define AIFLIB_ALWAYS_AVAIL  ((int)(sizeof(NU) - 1))                  /* 7  */
#define AIFLIB_PAYLOAD_SIZE  ((int)(sizeof(NU) + sizeof(void*) - 2))  /* 14 */
#define AIFLIB_HEAP_SLEN     255   /* heap-allocated long string  */
#define AIFLIB_STATIC_SLEN   254   /* static/literal long string  */
#define AIFLIB_LONGSTR_HDR   ((NI)(3 * sizeof(NI)))                   /* 24 */

/* ---- string / LongString layout (field names are hash-independent) ----
 *
 * `data_0` is a POINTER, not an inline flexible array: this is exactly what
 * aifc emits for a string-literal const (`.data_0 = "..."` -> pointer to the
 * literal, real storage), and it lets heap blocks be one allocation whose
 * `data_0` points just past the header (so freeing the header frees the data).
 * (Programs that *index* into a string are not yet supported — that path would
 * inline nimony's flexible-array `rawData`; none of aiflib's callers index.)
 */
typedef struct Aiflib_LongString {
  NI   fullLen_0;
  NI   rc_0;
  NI   capImpl_0;
  NC8* data_0;
} Aiflib_LongString;

typedef struct Aiflib_string {
  NU                 bytes_0;  /* LE: byte0 = slen, bytes 1.. = inline chars   */
  Aiflib_LongString* more_0;   /* reused as inline storage for the medium tier */
} Aiflib_string;

/* ---- seq[T] layout (mirror lib/std/system/seqimpl.nim) ---- */
typedef struct Aiflib_seq {
  NI    len_0;
  void* data_0;                /* ptr UncheckedArray[T]; cap from allocatedSize */
} Aiflib_seq;

/* ---- File (nimNativeIo: a raw OS file descriptor + flags) ---- */
typedef struct Aiflib_File {
  NI fd;
  NU flags;
} Aiflib_File;

extern Aiflib_File aiflib_stdout;
extern Aiflib_File aiflib_stderr;
extern Aiflib_File aiflib_stdin;

/* ---- memory / ARC ---- */
void* aiflib_alloc(NI size);
void* aiflib_alloc0(NI size);
void* aiflib_realloc(void* p, NI size);
void  aiflib_dealloc(void* p);
NI    aiflib_allocated_size(void* p);
void* aiflib_alloc_fixed(NI size);
void  aiflib_dealloc_fixed(void* p);
void  aiflib_arc_inc(NI* rc);
NB8   aiflib_arc_dec(NI* rc);
NB8   aiflib_arc_is_unique(NI* rc);

/* ---- strings ---- */
NI            aiflib_str_len(Aiflib_string s);
const NC8*    aiflib_str_data(const Aiflib_string* s);
Aiflib_string aiflib_str_from_bytes(const NC8* p, NI n);
Aiflib_string aiflib_str_concat(Aiflib_string a, Aiflib_string b);
Aiflib_string aiflib_str_slice_ab(Aiflib_string s, NI first, NI last);
NC8           aiflib_str_index(Aiflib_string s, NI i);
void          aiflib_str_index_set(Aiflib_string* s, NI i, NC8 c);
Aiflib_string aiflib_new_string(NI n);
NB8           aiflib_str_eq(Aiflib_string a, Aiflib_string b);
NI            aiflib_str_cmp(Aiflib_string a, Aiflib_string b);
NB8           aiflib_str_lt(Aiflib_string a, Aiflib_string b);
NB8           aiflib_str_le(Aiflib_string a, Aiflib_string b);
void          aiflib_str_add_char(Aiflib_string* s, NC8 c);
void          aiflib_str_add_str(Aiflib_string* s, Aiflib_string part);
Aiflib_string aiflib_dollar_int(NI64 x);
Aiflib_string aiflib_dollar_uint(NU64 x);
Aiflib_string aiflib_dollar_bool(NB8 b);
void          aiflib_str_destroy(Aiflib_string s);
void          aiflib_str_copy(Aiflib_string* dest, Aiflib_string src);
Aiflib_string aiflib_str_dup(Aiflib_string s);
void          aiflib_str_was_moved(Aiflib_string* s);

/* ---- IO (syncio) ---- */
void aiflib_write_string(Aiflib_File f, Aiflib_string s);
void aiflib_write_char(Aiflib_File f, NC8 c);
void aiflib_write_int(Aiflib_File f, NI64 x);
void aiflib_write_uint(Aiflib_File f, NU64 x);
void aiflib_write_bool(Aiflib_File f, NB8 b);
void aiflib_write_float(Aiflib_File f, NF64 x);
void aiflib_flush_std_streams(void);

/* ---- panics / checks / OOM (system/panics.nim, system/memory.nim) ---- */
NI   aiflib_icheck_b(NI i, NI b);        /* nimIcheckB:  [0,b] -> i;   else panic */
NI   aiflib_icheck_ab(NI i, NI a, NI b); /* nimIcheckAB: [a,b] -> i-a; else panic */
NU   aiflib_ucheck_b(NU i, NU b);        /* nimUcheckB:  unsigned i<=b -> i        */
NU   aiflib_ucheck_ab(NU i, NU a, NU b); /* nimUcheckAB: unsigned i-a<=b -> i-a     */
void aiflib_panic(Aiflib_string s);    /* write s to stderr, exit 1 (noreturn)*/
void aiflib_oom_handler(NI size);      /* default: continue-after-OOM (no-op)*/

/* ---- seq growth (system/seqimpl.nim) ---- */
NI   aiflib_recalc_cap(NI oldCap, NI added);

/* ---- module init (system/syncio `ini`): no-op; the C runtime self-inits. ---- */
void aiflib_noop(void);

#endif /* AIFLIB_H */
