/* aowllib.h — the aowl system runtime for the aoughwl native backend.
 *
 * Hand-written C runtime that provides the `system` / `syncio` symbols a
 * post-hexer `.c.nif` references, so real nimony programs link natively
 * through aifc (https://github.com/aoughwl/aifc) with no nimony `system.c.nif`.
 *
 * Per the aoughwl convention this hand-written C is the *bootstrap seed &
 * oracle* for the eventual aowl-native `system` module.
 *
 * Canonical types & entry points are named `aowllib_*` / `Aowllib*` and are
 * hash-independent.  A per-program shim (generated by bin/aowllib-cc) aliases
 * the module-hashed names a given `.c.nif` uses (e.g. `write_0_syn1lfpjv`) onto
 * these.  See docs/runtime.md.
 */
#ifndef AOWLLIB_H
#define AOWLLIB_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* ---- NIF primitive typedefs (mirror aifc's PRELUDE; C11 permits identical
 *      typedef redefinition, so co-inclusion with aifc output is safe). ---- */
typedef unsigned char NC8;
typedef uint16_t NC16;
typedef uint32_t NC32;
typedef float  NF32;
typedef double NF64;
typedef double NF;
typedef int8_t  NI8;  typedef int16_t  NI16; typedef int32_t  NI32; typedef int64_t  NI64;
typedef uint8_t NU8;  typedef uint16_t NU16; typedef uint32_t NU32; typedef uint64_t NU64;
typedef NI64 NI;      typedef NU64 NU;
typedef _Bool NB8;

/* ---- SSO string constants (mirror lib/std/system/stringimpl.nim) ---- */
#define AOWLLIB_ALWAYS_AVAIL  ((int)(sizeof(NU) - 1))                  /* 7  */
#define AOWLLIB_PAYLOAD_SIZE  ((int)(sizeof(NU) + sizeof(void*) - 2))  /* 14 */
#define AOWLLIB_HEAP_SLEN     255   /* heap-allocated long string  */
#define AOWLLIB_STATIC_SLEN   254   /* static/literal long string  */
#define AOWLLIB_LONGSTR_HDR   ((NI)(3 * sizeof(NI)))                   /* 24 */

/* ---- string / LongString layout (field names are hash-independent) ----
 *
 * `data_0` is a POINTER, not an inline flexible array: this is exactly what
 * aifc emits for a string-literal const (`.data_0 = "..."` -> pointer to the
 * literal, real storage), and it lets heap blocks be one allocation whose
 * `data_0` points just past the header (so freeing the header frees the data).
 * (Programs that *index* into a string are not yet supported — that path would
 * inline nimony's flexible-array `rawData`; none of aowllib's callers index.)
 */
typedef struct Aowllib_LongString {
  NI   fullLen_0;
  NI   rc_0;
  NI   capImpl_0;
  NC8* data_0;
} Aowllib_LongString;

typedef struct Aowllib_string {
  NU                 bytes_0;  /* LE: byte0 = slen, bytes 1.. = inline chars   */
  Aowllib_LongString* more_0;   /* reused as inline storage for the medium tier */
} Aowllib_string;

/* ---- seq[T] layout (mirror lib/std/system/seqimpl.nim) ---- */
typedef struct Aowllib_seq {
  NI    len_0;
  void* data_0;                /* ptr UncheckedArray[T]; cap from allocatedSize */
} Aowllib_seq;

/* ---- File (nimNativeIo: a raw OS file descriptor + flags) ---- */
typedef struct Aowllib_File {
  NI fd;
  NU flags;
} Aowllib_File;

extern Aowllib_File aowllib_stdout;
extern Aowllib_File aowllib_stderr;
extern Aowllib_File aowllib_stdin;

/* ---- memory / ARC ---- */
void* aowllib_alloc(NI size);
void* aowllib_alloc0(NI size);
void* aowllib_realloc(void* p, NI size);
void  aowllib_dealloc(void* p);
NI    aowllib_allocated_size(void* p);
void* aowllib_alloc_fixed(NI size);
void  aowllib_dealloc_fixed(void* p);
void  aowllib_arc_inc(NI* rc);
NB8   aowllib_arc_dec(NI* rc);
NB8   aowllib_arc_is_unique(NI* rc);

/* ---- strings ---- */
NI            aowllib_str_len(Aowllib_string s);
const NC8*    aowllib_str_data(const Aowllib_string* s);
Aowllib_string aowllib_str_from_bytes(const NC8* p, NI n);
Aowllib_string aowllib_str_concat(Aowllib_string a, Aowllib_string b);
Aowllib_string aowllib_str_slice_ab(Aowllib_string s, NI first, NI last);
NC8           aowllib_str_index(Aowllib_string s, NI i);
void          aowllib_str_index_set(Aowllib_string* s, NI i, NC8 c);
Aowllib_string aowllib_new_string(NI n);
NB8           aowllib_str_eq(Aowllib_string a, Aowllib_string b);
NI            aowllib_str_cmp(Aowllib_string a, Aowllib_string b);
NB8           aowllib_str_lt(Aowllib_string a, Aowllib_string b);
NB8           aowllib_str_le(Aowllib_string a, Aowllib_string b);
void          aowllib_str_add_char(Aowllib_string* s, NC8 c);
void          aowllib_str_add_str(Aowllib_string* s, Aowllib_string part);
Aowllib_string aowllib_dollar_int(NI64 x);
Aowllib_string aowllib_dollar_uint(NU64 x);
Aowllib_string aowllib_dollar_bool(NB8 b);
void          aowllib_str_destroy(Aowllib_string s);
void          aowllib_str_copy(Aowllib_string* dest, Aowllib_string src);
Aowllib_string aowllib_str_dup(Aowllib_string s);
void          aowllib_str_was_moved(Aowllib_string* s);

/* ---- IO (syncio) ---- */
void aowllib_write_string(Aowllib_File f, Aowllib_string s);
void aowllib_write_char(Aowllib_File f, NC8 c);
void aowllib_write_int(Aowllib_File f, NI64 x);
void aowllib_write_uint(Aowllib_File f, NU64 x);
void aowllib_write_bool(Aowllib_File f, NB8 b);
void aowllib_write_float(Aowllib_File f, NF64 x);
void aowllib_flush_std_streams(void);

/* ---- panics / checks / OOM (system/panics.nim, system/memory.nim) ---- */
NI   aowllib_icheck_b(NI i, NI b);        /* nimIcheckB:  [0,b] -> i;   else panic */
NI   aowllib_icheck_ab(NI i, NI a, NI b); /* nimIcheckAB: [a,b] -> i-a; else panic */
NU   aowllib_ucheck_b(NU i, NU b);        /* nimUcheckB:  unsigned i<=b -> i        */
NU   aowllib_ucheck_ab(NU i, NU a, NU b); /* nimUcheckAB: unsigned i-a<=b -> i-a     */
void aowllib_panic(Aowllib_string s);    /* write s to stderr, exit 1 (noreturn)*/
void aowllib_oom_handler(NI size);      /* default: continue-after-OOM (no-op)*/
void aowllib_chck_nil_disp(const void* p); /* method dispatch: nil-dispatcher guard */

/* ---- seq growth (system/seqimpl.nim) ---- */
NI   aowllib_recalc_cap(NI oldCap, NI added);

/* ---- module init (system/syncio `ini`): no-op; the C runtime self-inits. ---- */
void aowllib_noop(void);

#endif /* AOWLLIB_H */
